import type { Module } from "./types";

// Catálogo de módulos do hub. Adicionar módulo = adicionar item aqui.
// Nomes de módulos futuros são sugestões: cortar ou renomear a vontade.
export const modules: Module[] = [
  {
    slug: "abm",
    title: "ABM",
    summary:
      "Account-Based Marketing na prática: dois tiers, dois scores, esteiras de cadência e medição por conta.",
    status: "active",
    href: "/abm",
    icon: "Target",
    cover: "/brand/bg-liquid-blue.png",
    kicker: "Playbook",
    lessons: 11,
    duration: "~55 min",
  },
  {
    slug: "crm",
    title: "CRM no HubSpot",
    summary:
      "Playbook e treinamento de HubSpot: como operar o CRM, propriedades, listas, workflows e relatórios.",
    status: "coming-soon",
    href: "/crm",
    icon: "Database",
    cover: "/brand/bg-network.jpg",
    kicker: "Playbook",
  },
  {
    slug: "prospeccao-outbound",
    title: "Prospecção Outbound",
    summary: "Motor de prospecção ativa e cadências frias.",
    status: "coming-soon",
    icon: "Send",
    cover: "/brand/bg-rays.jpg",
    kicker: "Trilha",
  },
  {
    slug: "discovery-qualificacao",
    title: "Discovery & Qualificação",
    summary: "Descoberta de dor e qualificação de oportunidade.",
    status: "coming-soon",
    icon: "Search",
    cover: "/brand/bg-mesh-purple.jpg",
    kicker: "Trilha",
  },
  {
    slug: "objecoes",
    title: "Objeções",
    summary: "Biblioteca de objeções e respostas.",
    status: "coming-soon",
    icon: "MessageSquareWarning",
    cover: "/brand/bg-8.jpg",
    kicker: "Consulta",
  },
  {
    slug: "propostas-pricing",
    title: "Propostas & Pricing",
    summary: "Estrutura de proposta, faseamento e preço.",
    status: "coming-soon",
    icon: "FileText",
    cover: "/brand/bg-liquid-deep.png",
    kicker: "Trilha",
  },
  {
    slug: "solution-packs",
    title: "Solution Packs",
    summary: "Pacotes de solução por dor e segmento.",
    status: "coming-soon",
    icon: "Package",
    cover: "/brand/bg-liquid-3.png",
    kicker: "Consulta",
  },
  {
    slug: "cases-prova-social",
    title: "Cases & Prova Social",
    summary: "Casos, resultados e provas por indústria.",
    status: "coming-soon",
    icon: "Award",
    cover: "/brand/bg-7.jpg",
    kicker: "Consulta",
  },
  {
    slug: "eventos-field",
    title: "Eventos & Field",
    summary: "Roundtables, eventos e captura de intenção.",
    status: "coming-soon",
    icon: "CalendarDays",
    cover: "/brand/bg-mesh-purple.jpg",
    kicker: "Trilha",
  },
];
